### ISSUE TITLE
Automate semantic version updates for GatorGradle

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/java-assigment-starter#3]
It would be a good idea if we developed an approach that automated changes to the semantic version of GatorGradle in the `build.gradle` configuration for all of our sample assignments, especially given the fact that we are going to have more sample assignments in the future!

**Comment by Michionlion** [comment]
Since the correct version has been set, I will change this issue to address the automation of this configuration change.

**Comment by Michionlion** [comment]
I've fixed this by using a buildscript method to ensure that the newest version of GatorGradle is always used.
